### ISSUE TITLE
LinterGjslint.Linter is deprecated.

### ISSUE THREAD

**Issue by dereknex** [AtomLinter/linter-gjslint#15] opened 2015-07-22 05:09 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API

```
LinterGjslint.Linter (/Users/derek/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterGjslint (/Users/derek/.atom/packages/linter-gjslint/lib/linter-gjslint.coffee:25:4)
Object.lint (/Users/derek/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/derek/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/derek/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/derek/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by Arcanemagus** [comment] 2015-10-14 21:01
Closing as a duplicate of #10.

**Closed as completed by Arcanemagus** 2015-10-14 21:01 UTC
